services:
  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - SENDER_EMAIL_PASSWORD=${SENDER_EMAIL_PASSWORD}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    command: ["python3", "-m", "src.main"]
    depends_on:
      - db
      - redis
      - elasticsearch

  db:
    image: postgres
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 1234:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: always

volumes:
  pgdata:
  pgadmin_data:
  esdata:
