"""all models

Revision ID: 2d21659585ce
Revises: 
Create Date: 2025-04-22 02:40:50.906717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d21659585ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_activation_tokens', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'email_activation_tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email_activation_tokens', type_='foreignkey')
    op.drop_column('email_activation_tokens', 'user_id')
    # ### end Alembic commands ###
