"""Message cascade

Revision ID: 653a11e41a7a
Revises: b3b9db09490e
Create Date: 2026-03-27 07:14:23.130254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '653a11e41a7a'
down_revision: Union[str, None] = 'b3b9db09490e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('messages_chat_id_fkey', 'messages', type_='foreignkey')
    op.drop_constraint('messages_user_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('read_statuses_user_id_fkey', 'read_statuses', type_='foreignkey')
    op.drop_constraint('read_statuses_message_id_fkey', 'read_statuses', type_='foreignkey')
    op.create_foreign_key(None, 'read_statuses', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'read_statuses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'read_statuses', type_='foreignkey')
    op.drop_constraint(None, 'read_statuses', type_='foreignkey')
    op.create_foreign_key('read_statuses_message_id_fkey', 'read_statuses', 'messages', ['message_id'], ['id'])
    op.create_foreign_key('read_statuses_user_id_fkey', 'read_statuses', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_user_id_fkey', 'messages', 'users', ['user_id'], ['id'])
    op.create_foreign_key('messages_chat_id_fkey', 'messages', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###
