"""folder nullalbe

Revision ID: 8508aeaa02bb
Revises: f8b2236837dd
Create Date: 2025-05-29 14:01:32.799460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8508aeaa02bb'
down_revision: Union[str, None] = 'f8b2236837dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'folder_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'folder_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
