"""pin in folder

Revision ID: 9ac6932916ba
Revises: f9e4e2c0ab82
Create Date: 2025-06-08 13:47:23.297488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ac6932916ba'
down_revision: Union[str, None] = 'f9e4e2c0ab82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folder_chat_associations', sa.Column('is_pinned', sa.Boolean(), nullable=False))
    op.drop_column('user_chat_associations', 'is_pinned')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_chat_associations', sa.Column('is_pinned', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('folder_chat_associations', 'is_pinned')
    # ### end Alembic commands ###
