"""folder position

Revision ID: aaac7baebc8c
Revises: 8508aeaa02bb
Create Date: 2025-06-04 14:50:29.780801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaac7baebc8c'
down_revision: Union[str, None] = '8508aeaa02bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('position', sa.Integer(), nullable=False))
    op.alter_column('folders', 'name',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=16),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('folders', 'name',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_column('folders', 'position')
    # ### end Alembic commands ###
