"""ReadStatus updated_at

Revision ID: b3b9db09490e
Revises: 541722dbaa9f
Create Date: 2026-02-14 08:27:10.367098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3b9db09490e'
down_revision: Union[str, None] = '541722dbaa9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'message_type')
    op.add_column('read_statuses', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('read_statuses', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('read_statuses', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('read_statuses', 'updated_at')
    op.add_column('messages', sa.Column('message_type', postgresql.ENUM('TEXT', 'FILE', 'BOTH', name='messagetype'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
