"""is_open_for_messages, is_visible nullable in chats/models.py

Revision ID: e70a4bc9dd65
Revises: 09cbad3eb8b0
Create Date: 2025-10-13 06:31:26.872987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e70a4bc9dd65'
down_revision: Union[str, None] = '09cbad3eb8b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'is_open_for_messages',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('chats', 'is_visible',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'is_visible',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('chats', 'is_open_for_messages',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
