"""associations

Revision ID: e8ce74ec16ea
Revises: 
Create Date: 2025-05-21 19:25:32.286353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8ce74ec16ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_chat_associations',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'chat_id')
    )
    op.drop_table('user_chat_association_table')
    op.drop_column('chats', 'is_pinned_up')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('chats', sa.Column('is_pinned_up', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_table('user_chat_association_table',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name='user_chat_association_table_chat_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_chat_association_table_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'chat_id', name='user_chat_association_table_pkey')
    )
    op.drop_table('user_chat_associations')
    # ### end Alembic commands ###
