"""chats name

Revision ID: f8b2236837dd
Revises: e8ce74ec16ea
Create Date: 2025-05-29 13:54:51.897734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8b2236837dd'
down_revision: Union[str, None] = 'e8ce74ec16ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('chats', sa.Column('description', sa.String(length=100), nullable=True))
    op.add_column('chats', sa.Column('avatar', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'chats', ['uuid'])
    op.create_unique_constraint(None, 'messages', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='unique')
    op.drop_constraint(None, 'chats', type_='unique')
    op.drop_column('chats', 'avatar')
    op.drop_column('chats', 'description')
    op.drop_column('chats', 'name')
    # ### end Alembic commands ###
