"""folder and chat many to many

Revision ID: f9e4e2c0ab82
Revises: 156bc62ed69b
Create Date: 2025-06-07 21:55:01.492291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9e4e2c0ab82'
down_revision: Union[str, None] = '156bc62ed69b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder_chat_associations',
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.PrimaryKeyConstraint('folder_id', 'chat_id')
    )
    op.drop_constraint('chats_folder_id_fkey', 'chats', type_='foreignkey')
    op.drop_column('chats', 'folder_id')
    op.create_unique_constraint(None, 'email_activation_tokens', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email_activation_tokens', type_='unique')
    op.add_column('chats', sa.Column('folder_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('chats_folder_id_fkey', 'chats', 'folders', ['folder_id'], ['id'])
    op.drop_table('folder_chat_associations')
    # ### end Alembic commands ###
